# Generated by Django 4.1.3 on 2022-12-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text_box', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ValueSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('titles', models.TextField(max_length=255)),
                ('urls', models.TextField(max_length=255)),
                ('price', models.TextField(max_length=255)),
            ],
        ),
    ]
