# Generated by Django 4.1.3 on 2022-12-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuesearch',
            name='urls',
            field=models.TextField(max_length=2550),
        ),
    ]
